CREATE OR REPLACE VIEW VIEW_ACIDENTES_POR_LOCALIDADE (LOCALIDADE, TOTAL_ACIDENTES) AS
SELECT LOCALIDADE        AS LOCALIDADE, 
       COUNT(LOCALIDADE) AS TOTAL_ACIDENTES 
    FROM (SELECT BR||' NO QUILÔMETRO '||KM|| ', NO MUNICIPIO '|| MUNICIPIO  AS LOCALIDADE
            FROM SYSTEM.TB_ACIDENTES)
  GROUP BY LOCALIDADE
  ORDER BY COUNT(LOCALIDADE)DESC;