CREATE OR REPLACE VIEW VIEW_PERCENTUAL_ACIDENTES_POR_UF(UF,PERCENTUAL_POR_ESTADO)AS 
SELECT UF,
       ROUND(COUNT(UF)/(SELECT COUNT(UF) FROM TB_ACIDENTES)*100,2) AS  PERCENTUAL_POR_ESTADO
    FROM SYSTEM.TB_ACIDENTES
  GROUP BY UF;