CREATE OR REPLACE VIEW VIEW_INDICADOR_VITIMAS_ANUAL_UF (ANO_ACIDENTE,ESTADO,QTD_VITIMAS,QTD_OBITOS,QTD_FERIDOS_LEVEMENTE,QTD_FERIDOS_GRAVEMENTE,QTD_ILESOS,QTD_VITIMAS_FERIDAS,QTD_VEICULOS_ENVOLVIDOS)AS 
SELECT  TRUNC(DATA_ACIDENTE,'YYYY') AS ANO_ACIDENTE,
        UF                  AS ESTADO,
        SUM(PESSOAS)        AS QTD_VITIMAS,
        SUM(MORTOS)         AS QTD_OBITOS,
        SUM(FERIDOS_LEVES)  AS QTD_FERIDOS_LEVEMENTE,
        SUM(FERIDOS_GRAVES) AS QTD_FERIDOS_GRAVEMENTE,
        SUM(ILESOS)         AS QTD_ILESOS,
        SUM(FERIDOS)        AS QTD_VITIMAS_FERIDAS,
        SUM(VEICULOS)       AS QTD_VEICULOS_ENVOLVIDOS
    FROM SYSTEM.TB_ACIDENTES   
 GROUP BY UF,
          TRUNC(DATA_ACIDENTE,'YYYY');