-- INSERÇÃO DE GEOMETRIAS PONTUAIS
CREATE OR REPLACE PROCEDURE PROC_INSERIR_GEOMETRIAS_PONTUAIS
AS 
    VGEOM SDO_GEOMETRY;
    VCONTADOR NUMBER := 0;
BEGIN
    FOR C1 IN (SELECT PID, ROWID, LATITUDE, LONGITUDE FROM SYSTEM.TB_ACIDENTES)
    LOOP
        BEGIN
            SELECT MDSYS.SDO_GEOMETRY(2001,4326, MDSYS.SDO_POINT_TYPE(C1.LONGITUDE,C1.LATITUDE,NULL),NULL,NULL)
              INTO VGEOM
                FROM SYSTEM.TB_ACIDENTES A
              WHERE C1.LATITUDE IS NOT NULL 
                AND C1.LONGITUDE IS NOT NULL
                AND A.ROWID = C1.ROWID
                AND A.PID = C1.PID;

        EXCEPTION WHEN OTHERS THEN
            VGEOM := NULL;
        END;

        UPDATE SYSTEM.TB_ACIDENTES A
            SET A.GEOMETRY = VGEOM
          WHERE C1.LATITUDE IS NOT NULL 
            AND C1.LONGITUDE IS NOT NULL
            AND A.ROWID = C1.ROWID
            AND A.PID = C1.PID;

         VCONTADOR  := VCONTADOR +1;

         IF MOD(VCONTADOR,1000) = 0 THEN
          COMMIT;
         END IF; 
    END LOOP;
    COMMIT;
END;
/